### PR TITLE
chore: update project URL

### PR DESCRIPTION
**Pull request by pcaversaccio**
As title. I was reading your [PyPI description](https://pypi.org/project/ape-flashbots) and realised that your URLs are not correct.

### CODE REVIEW

**Comment by pcaversaccio** [comment]
@fubuloubu can we get this merged?

**Comment by fubuloubu** [comment]
Not sure if the idea was eventually to move it to ApeWorX org

**Comment by pcaversaccio** [comment]
I see, @johnson2427? If you plan to move it to ApeWorX please close this PR. Just saying that the current URLs are pointing to the wrong target.

**Comment by fubuloubu** [comment]
> I see, @johnson2427? If you plan to move it to ApeWorX please close this PR. Just saying that the current URLs are pointing to the wrong target.

@unparalleled-js took over from him, so we will talk about transitioning over to ApeWorX org once it's working (it's not currently working)

**Comment by pcaversaccio** [comment]
right, so I guess if this is the plan, we can close the PR after the decision is made.

**Comment by pcaversaccio** [comment]
Closing since it's planned to be moved back to `ApeWorX` once it's working.

**Pull request closed without merging**
